### ISSUE TITLE
One difficult issue

### ISSUE THREAD

**Issue by eshimischi** [wonderful-panda/vue-vtable#1]
Hi, i'm studying Typescript and Vue by using your projects, thanks for this. 
Tried to update this lib to the latest and have one issue, i cannot solve it by myself.

vue-typed-component 0.9.0
vue-tsx-support 1.0.0
vue 2.5.3
vue-class-component 6.1.0

**vlist.tsx** line 25
https://github.com/wonderful-panda/vue-vtable/blob/09b86d1d536b56853bd4178bc33725cb6b2fc4f7/src/vlist.tsx#L25

Argument (NumberConstruction | StringConstruction)[] cannot be assigned to prop type Prop<{}>

and Prop<{}> is new (...args: any[]) => object & {}

any tips? @wonderful-panda 

Arigatou!

**Comment by wonderful-panda** [comment]
This project is broken now.

`vue-typed-component/props` (`p` in `vlist.tsx`) has problem when using with Vue 2.5.
So, I'll remove it from `vue-typed-component`, and writing alternative library which works with Vue 2.5
([Here](https://github.com/wonderful-panda/vue-strict-prop), not released yet)

I'll fix this project with it in a few days.

**Comment by eshimischi** [comment]
@wonderful-panda So, vue-typed-component library will be deprecated?

**Comment by wonderful-panda** [comment]
No, remove `props` (undocumented api in vue-typed-component) only.

**Comment by eshimischi** [comment]
@wonderful-panda yeah, i got it, thanks for information.
